
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /api/v1/auth/** ,/api/v1/user/**


        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/v1/book/**
          filters:
              - AuthenticationFilter




server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

