spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/user-cap?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456asd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: USER-SERVICE

server:
  port: 8084
  error:
    include-binding-errors: always
    include-message: always
